// clang-format off
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arctos6135_robotpathfinder_core_path_Path */

#ifndef _Included_com_arctos6135_robotpathfinder_core_path_Path
#define _Included_com_arctos6135_robotpathfinder_core_path_Path
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    _construct
 * Signature: ([Lcom/arctos6135/robotpathfinder/core/Waypoint;DI)V
 */
JNIEXPORT void JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path__1construct
  (JNIEnv *, jobject, jobjectArray, jdouble, jint);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    _destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path__1destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    _setBaseRadius
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path__1setBaseRadius
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    _setBackwards
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path__1setBackwards
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    at
 * Signature: (D)Lcom/arctos6135/robotpathfinder/math/Vec2D;
 */
JNIEXPORT jobject JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path_at
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    derivAt
 * Signature: (D)Lcom/arctos6135/robotpathfinder/math/Vec2D;
 */
JNIEXPORT jobject JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path_derivAt
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    secondDerivAt
 * Signature: (D)Lcom/arctos6135/robotpathfinder/math/Vec2D;
 */
JNIEXPORT jobject JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path_secondDerivAt
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    wheelsAt
 * Signature: (D)Lcom/arctos6135/robotpathfinder/util/Pair;
 */
JNIEXPORT jobject JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path_wheelsAt
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    _computeLen
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path__1computeLen
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    _s2T
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path__1s2T
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    _t2S
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path__1t2S
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    _mirrorLeftRight
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path__1mirrorLeftRight
  (JNIEnv *, jobject);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    _mirrorFrontBack
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path__1mirrorFrontBack
  (JNIEnv *, jobject);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    _retrace
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path__1retrace
  (JNIEnv *, jobject);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    _updateWaypoints
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path__1updateWaypoints
  (JNIEnv *, jobject);

/*
 * Class:     com_arctos6135_robotpathfinder_core_path_Path
 * Method:    _update
 * Signature: (DDDDDDD)V
 */
JNIEXPORT void JNICALL Java_com_arctos6135_robotpathfinder_core_path_Path__1update
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
// clang-format on
