// clang-format off
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arctos6135_robotpathfinder_core_lifecycle_JNIObjectReference */

#ifndef _Included_com_arctos6135_robotpathfinder_core_lifecycle_JNIObjectReference
#define _Included_com_arctos6135_robotpathfinder_core_lifecycle_JNIObjectReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arctos6135_robotpathfinder_core_lifecycle_JNIObjectReference
 * Method:    _freeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_arctos6135_robotpathfinder_core_lifecycle_JNIObjectReference__1freeObject
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
