/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class robot_pathfinder_core_path_JNIPath */

#ifndef _Included_robot_pathfinder_core_path_JNIPath
#define _Included_robot_pathfinder_core_path_JNIPath
#ifdef __cplusplus
extern "C" {
#endif
#undef robot_pathfinder_core_path_JNIPath_PT_BEZIER
#define robot_pathfinder_core_path_JNIPath_PT_BEZIER 1L
#undef robot_pathfinder_core_path_JNIPath_PT_CUBIC_HERMITE
#define robot_pathfinder_core_path_JNIPath_PT_CUBIC_HERMITE 2L
#undef robot_pathfinder_core_path_JNIPath_PT_QUINTIC_HERMITE
#define robot_pathfinder_core_path_JNIPath_PT_QUINTIC_HERMITE 3L
/*
 * Class:     robot_pathfinder_core_path_JNIPath
 * Method:    _construct
 * Signature: ([Lrobot/pathfinder/core/JNIWaypoint;DI)V
 */
JNIEXPORT void JNICALL Java_robot_pathfinder_core_path_JNIPath__1construct
  (JNIEnv *, jobject, jobjectArray, jdouble, jint);

/*
 * Class:     robot_pathfinder_core_path_JNIPath
 * Method:    _setBaseRadius
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_robot_pathfinder_core_path_JNIPath__1setBaseRadius
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     robot_pathfinder_core_path_JNIPath
 * Method:    _setBackwards
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_robot_pathfinder_core_path_JNIPath__1setBackwards
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
